config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root to: 'posts#index'
  devise_for :users
  resources :users

  namespace :admin do
    resources :posts, except: %i[index show]
  end

  resources :posts, only: %i[index show] do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :owner, class_name: 'User', foreign_key: 'user_id'
  belongs_to :post

  validates_presence_of :content
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploaders :images, ImageUploader

  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :owner, class_name: 'User', foreign_key: 'user_id'
  has_many :comments, dependent: :destroy

  validates_uniqueness_of :title
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, through: :posts, dependent: :destroy

  enum role: %i[user admin]
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < ApplicationController
    before_action { authorize Post }

    def new
      @form = PostForm.new(Post.new, {})
    end

    def create
      @form = PostForm.new(Post.new, post_params.merge({user_id: current_user.id}))
      if @form.save
        flash[:notice] = 'Post succesfully added'
        redirect_to @form
      else
        flash[:danger] = 'Something went wrong'
        render 'new'
      end
    end

    def edit
      @post = Post.friendly.find(params[:id])
      @form = PostForm.new(@post, {})
    end

    def update
      @post = Post.friendly.find(params[:id])
      @form = PostForm.new(@post, post_params.merge({user_id: current_user.id}))
      if @form.save
        flash[:notice] = 'Post succesfully updated'
        redirect_to @form
      else
        flash[:danger] = 'Something went wrong'
        render 'edit'
      end
    end

    def destroy
      @post = Post.friendly.find(params[:id])
      @post.destroy
      flash[:notice] = 'Post succesfully deleted'
      redirect_to root_path
    end

    private

    def post_params
      params.require(:post).permit(:title, :content, { images: [] })
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action'
    redirect_to root_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    authorize Comment
    @post = Post.friendly.find(params[:post_id])
    @comment = Comment.new
  end

  def edit
    @post = Post.friendly.find(params[:post_id])
    @comment = Comment.find(params[:id])
    authorize @comment
  end

  def create
    @post = Post.friendly.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.owner = current_user
    authorize @comment
    if @comment.save
      flash[:notice] = 'Comment succesfully added'
    else
      flash[:danger] = 'Something went wrong'
    end
    redirect_to post_path(@post)
  end

  def update
    @post = Post.friendly.find(params[:post_id])
    @comment = Comment.find(params[:id])
    authorize @comment
    if @comment.update(comment_params)
      flash[:notice] = 'Comment succesfully updated'
    else
      flash[:danger] = 'Something went wrong'
    end
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.friendly.find(params[:post_id])
    @comment = Comment.find(params[:id])
    authorize @comment
    @comment.destroy
    flash[:notice] = 'Comment succesfully deleted'
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action { authorize Post }

  def index
    @posts = Post.all
  end

  def show
    @post = Post.friendly.find(params[:id])
    @comment = Comment.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/posts/_form.html.slim
= form_for [:admin, @form] do |f|
  = render 'form_errors'
  = f.label :title
  = f.text_field :title
  = f.cktext_area :content, id: 'content'
  = f.label :images
  = f.file_field :images, multiple: true

  = f.submit 'Add'

app/views/admin/posts/_form_errors.html.slim
- if @form.errors.any?
  - @form.errors.full_messages.each do |msg|
    .alert.alert-danger
      = msg

app/views/admin/posts/edit.html.slim
= render 'form'

app/views/admin/posts/new.html.slim
= render 'form'

app/views/comments/_form.html.slim
= form_for [post, comment] do |f|
  = f.cktext_area :content, id: 'content'
  = f.submit 'Add', class: 'btn btn-lg btn-primary btn-block'

app/views/comments/_form_errors.html.slim
- if comment.errors.any?
  - comment.errors.full_messages.each do |msg|
    .alert.alert-danger
      = msg

app/views/comments/_listed_comments.html.slim
ul
  - post.comments.each do |comment|
    = content_tag(:div, id: comment.id) do
      hr
      .row
        p= comment.owner.email
        - if policy(comment).destroy?
          = link_to 'delete', post_comment_path(post, comment), method: :delete, class: 'btn btn-secondary'
        - if policy(comment).update?
          = link_to 'edit', edit_post_comment_path(post, comment), class: 'btn btn-secondary'
      .row
        h3= comment.content.html_safe

app/views/comments/edit.html.slim
= render 'form', post: @post, comment: @comment

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 4.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Edit account', edit_user_registration_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link' %></li>
<% else %>
  <li class='nav-item'><%= link_to 'Log in', new_user_session_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Register', new_user_registration_path, class: 'nav-link' %></li>
<% end %>

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-toggleable-md.navbar-light.bg-faded
  button.navbar-toggler.navbar-toggler-right aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  - if current_user
    p.navbar-brand
      = "#{current_user.email} - #{current_user.role}"
  button
    = link_to 'Home', root_path
  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      = render 'layouts/navigation_links'
      = render 'layouts/nav_links_for_auth'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Zadanie1'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Zadanie1'}"
    == stylesheet_link_tag "application", :media => 'all'
    == javascript_include_tag 'application'
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/posts/_form.html.slim
= form_for @post do |f|
  = render 'form_errors'
  = f.label :title
  = f.text_field :title
  = f.cktext_area :content, value: 'content', id: 'content'
  = f.label :images
  = f.file_field :images, multiple: true

  = f.submit 'Add'

app/views/posts/index.html.slim
= link_to 'Add post', new_admin_post_path, class: 'btn btn-primary btn-lg btn-block'

- @posts.each do |post|
  .container id=post.id
    .row
      h2 = link_to post.title, post_path(post)
    .row: h5
      small
        | By:
      = post.owner.email
    .row
      - if policy(:post).update?
        = link_to 'Edit', edit_admin_post_path(post), class: 'btn btn-primary btn-sm'
      - if policy(:post).destroy?
        = link_to 'Delete', admin_post_path(post), class: 'btn btn-danger btn-sm', method: :delete
    .row
      p = post.content.html_safe

    - if post.images?
      - post.images_urls.each do |url|
        = image_tag(url)
  hr

app/views/posts/show.html.slim
.container
  .row
    h1= @post.title

  .row
    h5
      small
        | By:
      = @post.owner.email

  .row
    .col
      - if policy(:post).update?
        = link_to 'Edit', edit_admin_post_path(@post), class: 'btn btn-primary'
      - if policy(:post).destroy?
        = link_to 'Delete', admin_post_path(@post), class: 'btn btn-danger', method: :delete

  hr
  p= @post.content.html_safe

  - if @post.images?
    - @post.images_urls.each do |url|
      = image_tag(url)

  hr
  h1 Comments:
  - if policy(:comment).create?
    = render 'comments/form', post: @post, comment: @comment
  - else
    h3 only logged in users can comment

  hr
  = render 'comments/listed_comments', post: @post

app/views/users/_user.html.erb
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>